export const CRM_PATHS = {
  root: "/cabinet/crm",
  denied: "/cabinet/crm/denied",
  dashboard: "/cabinet/crm/dashboard",
  people: "/cabinet/crm/people",
  relocation: "/cabinet/crm/relocation",
  students: "/cabinet/crm/students",
  employers: "/cabinet/crm/employers",
  tasks: "/cabinet/crm/tasks",
  communications: "/cabinet/crm/communications",
  notifications: "/cabinet/crm/notifications",
  reports: "/cabinet/crm/reports",
  settings: "/cabinet/crm/settings",
  settingsAccess: "/cabinet/crm/settings/access",
  settingsIntegrations: "/cabinet/crm/settings/integrations",
  settingsSecurity: "/cabinet/crm/settings/security",
  adminRoot: "/cabinet/crm/admin",
  adminUsers: "/cabinet/crm/admin/users",
  adminVacancies: "/cabinet/crm/admin/vacancies",
  adminStories: "/cabinet/crm/admin/stories",
  states: "/cabinet/crm/states",
  case: (caseId: string) => `/cabinet/crm/cases/${encodeURIComponent(caseId)}`,
} as const;
