export const cities = [
  {
    id: "murmansk",
    name: "Мурманск",
    longitude: 33.074970,
    latitude: 68.970665,
    eyebrow: "Столица региона",
    description: "Крупный арктический морской узел на Кольском заливе с глубоководным незамерзающим портом.",
    sectors: ["Морская логистика", "Рыбная отрасль", "Городские сервисы", "Туризм"],
    source: "https://invest.citymurmansk.ru/",
    labelOffset: { x: -78, y: -38 },
    markerOffset: { x: -22, y: 12 },
  },
  {
    id: "severomorsk",
    name: "Североморск",
    longitude: 33.419049,
    latitude: 69.075920,
    eyebrow: "Город-порт",
    description: "Город на Кольском заливе, связанный с обеспечением объектов и баз Северного флота.",
    sectors: ["Городская инфраструктура", "Транспорт", "Социальные сервисы"],
    note: "ЗАТО — действует особый режим доступа.",
    source: "https://gov-murman.ru/region/omsu/severomorsk/",
    labelOffset: { x: 16, y: -46 },
    markerOffset: { x: 24, y: -10 },
  },
  {
    id: "apatity",
    name: "Апатиты",
    longitude: 33.404392,
    latitude: 67.568626,
    eyebrow: "Наука и образование",
    description: "Научно-образовательный и геологический центр между Хибинами и озером Имандра.",
    sectors: ["Наука", "Образование", "Геология", "Транспорт"],
    source: "https://apatity.gov-murman.ru/city/eco-geo/",
    labelOffset: { x: -76, y: 22 },
    markerOffset: { x: -6, y: 24 },
  },
  {
    id: "monchegorsk",
    name: "Мончегорск",
    longitude: 32.931679,
    latitude: 67.939903,
    eyebrow: "Индустриальный центр",
    description: "Город на берегу Имандры, исторически сформированный вокруг освоения медно-никелевых руд.",
    sectors: ["Цветная металлургия", "Промышленный сервис", "Строительство"],
    source: "https://gov-murman.ru/region/omsu/monchegorsk/",
    labelOffset: { x: -96, y: -30 },
    markerOffset: { x: -24, y: 0 },
  },
  {
    id: "kandalaksha",
    name: "Кандалакша",
    longitude: 32.408272,
    latitude: 67.150790,
    eyebrow: "Южные ворота области",
    description: "Транспортный узел с железнодорожными, автомобильными и морскими связями через Белое море.",
    sectors: ["Железная дорога", "Морской транспорт", "Энергетика", "Промышленность"],
    source: "https://gov-murman.ru/region/omsu/kandalaksha/",
    labelOffset: { x: -94, y: 18 },
    markerOffset: { x: -24, y: 18 },
  },
  {
    id: "kirovsk",
    name: "Кировск",
    longitude: 33.663753,
    latitude: 67.615133,
    eyebrow: "Хибины",
    description: "Центр горнодобывающей отрасли и одно из ключевых туристических направлений региона.",
    sectors: ["Горная промышленность", "Переработка сырья", "Туризм", "Гостеприимство"],
    source: "https://kirovsk.ru/",
    labelOffset: { x: 18, y: -44 },
    markerOffset: { x: 26, y: 4 },
  },
  {
    id: "olenegorsk",
    name: "Оленегорск",
    longitude: 33.282597,
    latitude: 68.140732,
    eyebrow: "Железорудный центр",
    description: "Промышленный город Заполярья, выросший вокруг добычи и обогащения железосодержащих руд.",
    sectors: ["Добыча руды", "Обогащение", "Промышленный ремонт"],
    source: "https://olenegorsk.gov-murman.ru/city/",
    labelOffset: { x: 18, y: -22 },
    markerOffset: { x: 24, y: -8 },
  },
  {
    id: "kovdor",
    name: "Ковдор",
    longitude: 30.474108,
    latitude: 67.563049,
    eyebrow: "Юго-запад области",
    description: "Промышленный центр рядом с комплексным месторождением минерального сырья.",
    sectors: ["Горная добыча", "Минеральное сырьё", "Промышленный сервис"],
    source: "https://gov-murman.ru/region/omsu/kovdor/",
    labelOffset: { x: -62, y: -34 },
    markerOffset: { x: 0, y: 0 },
  },
  {
    id: "polyarnye-zori",
    name: "Полярные Зори",
    longitude: 32.501028,
    latitude: 67.365923,
    eyebrow: "Энергетический город",
    description: "Молодой город на берегу Имандры, сформированный вокруг Кольской АЭС.",
    sectors: ["Атомная энергетика", "Инженерия", "Городские сервисы"],
    source: "https://gov-murman.ru/region/omsu/pol_zori/",
    labelOffset: { x: 16, y: 12 },
    markerOffset: { x: -18, y: -8 },
  },
];
